### ISSUE TITLE
look and feel

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelgrove.github.io#1]
should be consistent with the HZ tool page.

**Comment by MichaelHilton** [comment]
do you mean colors? anything else? I'm open to suggestions if you have something specific, I can implement it.

**Comment by ivoysey** [comment]
color is what jumped out at me, and like margins and layout i guess? it's
just a really sharp change when you click through to HZ and that's a little
odd. this is obviously not urgent.

---Ian

**Comment by cyrus-** [comment]
are we happy with it now?

**Comment by ivoysey** [comment]
it's less jarring than it used to be after the main page got changed around a little bit, yeah. it still feels a little bolted onto the side but not so bad.

**Comment by cyrus-** [comment]
OK, closing this issue -- if you think of specific improvements we could make feel free to open another one.
