### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazelgrove.github.io#12]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by adamsmd** [comment]
Is this issue closable now?

Also, I think we should turn on "Enforce HTTPS" which automatically upgrades any HTTP connections to HTTPS.

**Comment by cyrus-** [comment]
Looks like it works, thanks! Just turned on "Enforce HTTPS".
