### ISSUE TITLE
links to and from HZ

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelgrove.github.io#2]
the links on the HZ page make sense for the AE submission but not so much in the context now

**Comment by cyrus-** [comment]
not sure what you mean?

**Comment by ivoysey** [comment]
i think i meant the three links on http://hazelgrove.org/implementation/hz.html. there's no way to get back to the main page, which might be nice? it's not really a problem; i don't totally remember what i thought could be improved.

**Comment by cyrus-** [comment]
put a link at the bottom to hazelgrove.org
