### ISSUE TITLE
automate updating of hz.js

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelgrove.github.io#3]
it'd be nice if we didn't have to manually copy the java script over from HZ anytime we made an update to the ocaml code. i don't know exactly what mechanism we'd use to do that, or how much of a pain it would be, or if it's worth it given how many times we might actually update the ocaml in the future.

**Comment by cyrus-** [comment]
I think we're gonna leave HZ itself in stasis now so not gonna bother with this for now.
