### ISSUE TITLE
add AEC brag

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelgrove.github.io#5]
they provide this file http://popl17.sigplan.org/getImage/orig/aec-badge-popl.png

**Comment by cyrus-** [comment]
don't really see an obvious place to put this -- I think its fine to leave the badge on the paper itself

**Comment by cyrus-** [comment]
that cool @ivoysey ?

**Comment by ivoysey** [comment]
yeah that seems fine


---Ian
